In [ ]:
import pandas as pd
import re
import numpy as np

# Load Data

In [ ]:
url = "https://raw.githubusercontent.com/naiarch/UTS-Big-Data-Web-Scraping-Lazada/main/product_watsons.csv"

df = pd.read_csv(url)
df.head()

,toko,kategori,nama_produk,harga,harga_original,harga_member,diskon,rating,jumlah_review,jumlah_terjual,lokasi,brand,url_produk,url_gambar,tanggal_scraping,halaman
0,Watsons,Facial,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900,91900.0,NaN,50.0,5.0,3.0,NaN,Indonesia,DERMACTION,https://www.watsons.co.id/id/dermaction-plus-p...,NaN,2026-05-07,0
1,Watsons,Facial,WATSONS Micellar Water Hydra 500ml,44900,99900.0,NaN,55.0,5.0,2.0,NaN,Indonesia,WATSONS,https://www.watsons.co.id/id/watsons-micellar-...,NaN,2026-05-07,0
2,Watsons,Facial,WATSONS Micellar Water Hydra 100ml,20900,29900.0,19855.0,30.0,NaN,0.0,NaN,Indonesia,WATSONS,https://www.watsons.co.id/id/watsons-micellar-...,https://www.watsons.co.id/assets/img/share/mem...,2026-05-07,0
3,Watsons,Facial,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900,289900.0,192755.0,30.0,NaN,0.0,NaN,Indonesia,COLLAGEN,https://www.watsons.co.id/id/collagen-by-watso...,https://www.watsons.co.id/assets/img/share/mem...,2026-05-07,0
4,Watsons,Facial,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900,99900.0,NaN,60.0,5.0,84.0,NaN,Indonesia,WATSONS,https://www.watsons.co.id/id/watsons-girlish-g...,NaN,2026-05-07,0

# Informasi Data

In [ ]:
df.tail()

,toko,kategori,nama_produk,harga,harga_original,harga_member,diskon,rating,jumlah_review,jumlah_terjual,lokasi,brand,url_produk,url_gambar,tanggal_scraping,halaman
9010,Watsons,Vitamin,BLACKMORES Blackmores Ultimate Omega Odourless...,374000,503000.0,NaN,NaN,5.0,62.0,NaN,Indonesia,BLACKMORES,https://www.watsons.co.id/id/blackmores-blackm...,NaN,2026-05-07,55
9011,Watsons,Vitamin,TRESNO JOYO Madu Tj Joybe Multi,10000,23900.0,NaN,NaN,5.0,67.0,NaN,Indonesia,TRESNO,https://www.watsons.co.id/id/tresno-joyo-madu-...,NaN,2026-05-07,56
9012,Watsons,Vitamin,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790,236600.0,NaN,NaN,NaN,0.0,NaN,Indonesia,NEWLAB+,https://www.watsons.co.id/id/newlab-brightlogy...,NaN,2026-05-07,57
9013,Watsons,Vitamin,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890,110600.0,NaN,NaN,NaN,0.0,NaN,Indonesia,NEWLAB+,https://www.watsons.co.id/id/newlab-brightlogy...,NaN,2026-05-07,57
9014,Watsons,Vitamin,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590,208600.0,NaN,NaN,NaN,0.0,NaN,Indonesia,NEWLAB+,https://www.watsons.co.id/id/newlab-brightlogy...,NaN,2026-05-07,57

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9015 entries, 0 to 9014
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   toko              9015 non-null   object
 1   kategori          9015 non-null   object
 2   nama_produk       9015 non-null   object
 3   harga             9015 non-null   int64
 4   harga_original    5487 non-null   float64
 5   harga_member      1673 non-null   float64
 6   diskon            4106 non-null   float64
 7   rating            5087 non-null   float64
 8   jumlah_review     8996 non-null   float64
 9   jumlah_terjual    0 non-null      float64
 10  lokasi            9015 non-null   object
 11  brand             9015 non-null   object
 12  url_produk        9015 non-null   object
 13  url_gambar        1673 non-null   object
 14  tanggal_scraping  9015 non-null   object
 15  halaman           9015 non-null   int64
dtypes: float64(6), int64(2), object(8)
memory usage: 1.1+ MB

# Cek Duplikasi Data

In [ ]:
df.duplicated().sum()

np.int64(0)

# Cek Missing Value

In [ ]:
df.isnull().sum()

toko                   0
kategori               0
nama_produk            0
harga                  0
harga_original      3528
harga_member        7342
diskon              4909
rating              3928
jumlah_review         19
jumlah_terjual      9015
lokasi                 0
brand                  0
url_produk             0
url_gambar          7342
tanggal_scraping       0
halaman                0
dtype: int64

# Cleaning Data

In [ ]:
# @title drop kolom
df = df.drop(columns=['kategori', 'harga_member', 'lokasi', 'brand', 'url_produk', 'url_gambar', 'tanggal_scraping', 'halaman'])
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000,503000.0,NaN,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000,23900.0,NaN,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790,236600.0,NaN,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890,110600.0,NaN,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590,208600.0,NaN,NaN,0.0,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9015 entries, 0 to 9014
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   toko            9015 non-null   object
 1   nama_produk     9015 non-null   object
 2   harga           9015 non-null   int64
 3   harga_original  5487 non-null   float64
 4   diskon          4106 non-null   float64
 5   rating          5087 non-null   float64
 6   jumlah_review   8996 non-null   float64
 7   jumlah_terjual  0 non-null      float64
dtypes: float64(5), int64(1), object(2)
memory usage: 563.6+ KB

In [ ]:
# @title cleaning harga

def clean_price(price):
    if pd.isna(price): return np.nan
    cleaned = (str(price).replace('Rp', '').replace('.', '').replace(',', '').strip())
    return float(cleaned)

df['harga'] = df['harga'].apply(clean_price)
df['harga_original'] = df['harga_original'].fillna(df['harga'])
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,NaN,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,NaN,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,NaN,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,NaN,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,NaN,NaN,0.0,NaN

In [ ]:
# @title cleaning diskon

def clean_discount(diskon):
    cleaned = re.sub(r'[^\d.]', '', str(diskon))
    if cleaned == '': return 0.0
    return float(cleaned)

df['diskon'] = df['diskon'].apply(clean_discount)
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,0.0,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,0.0,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,0.0,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,0.0,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,0.0,NaN,0.0,NaN

In [ ]:
# @title kolom jumlah_review
df['jumlah_review'] = pd.to_numeric(df['jumlah_review'], errors='coerce')
df['jumlah_review'] = df['jumlah_review'].fillna(0)
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,0.0,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,0.0,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,0.0,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,0.0,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,0.0,NaN,0.0,NaN

In [ ]:
# @title kolom jumlah_terjual

# jumlah_terjual tidak diimputasi karena data memang tidak tersedia dari platform
df['jumlah_terjual'] = pd.to_numeric(df['jumlah_terjual'], errors='coerce')
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,0.0,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,0.0,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,0.0,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,0.0,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,0.0,NaN,0.0,NaN

In [ ]:
# @title cleaning rating

# mengubah rating menjadi numerik
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,0.0,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,0.0,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,0.0,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,0.0,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,0.0,NaN,0.0,NaN

In [ ]:
# @title fixed column

# mengatur ulang urutan kolom
urutan_kolom = [
    'toko',
    'nama_produk',
    'harga',
    'harga_original',
    'diskon',
    'rating',
    'jumlah_review',
    'jumlah_terjual'
]

df = df[urutan_kolom]
df

,toko,nama_produk,harga,harga_original,diskon,rating,jumlah_review,jumlah_terjual
0,Watsons,DERMACTION PLUS Potent Triple Vitamin C Whip F...,45900.0,91900.0,50.0,5.0,3.0,NaN
1,Watsons,WATSONS Micellar Water Hydra 500ml,44900.0,99900.0,55.0,5.0,2.0,NaN
2,Watsons,WATSONS Micellar Water Hydra 100ml,20900.0,29900.0,30.0,NaN,0.0,NaN
3,Watsons,COLLAGEN BY WATSONS Hydro Balance Aqua Balm 9g,202900.0,289900.0,30.0,NaN,0.0,NaN
4,Watsons,WATSONS Girlish Gentle & Mild Micellar Cleansi...,39900.0,99900.0,60.0,5.0,84.0,NaN
...,...,...,...,...,...,...,...,...
9010,Watsons,BLACKMORES Blackmores Ultimate Omega Odourless...,374000.0,503000.0,0.0,5.0,62.0,NaN
9011,Watsons,TRESNO JOYO Madu Tj Joybe Multi,10000.0,23900.0,0.0,5.0,67.0,NaN
9012,Watsons,NEWLAB+ Brightlogy Glutacoll 5500 15'S,153790.0,236600.0,0.0,NaN,0.0,NaN
9013,Watsons,NEWLAB+ Brightlogy C-Gluta 360 Mini 7'S,71890.0,110600.0,0.0,NaN,0.0,NaN
9014,Watsons,NEWLAB+ Brightlogy C-Gluta 360 15'S,135590.0,208600.0,0.0,NaN,0.0,NaN

# Informasi Dataset Setelah Cleaning

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9015 entries, 0 to 9014
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   toko            9015 non-null   object
 1   nama_produk     9015 non-null   object
 2   harga           9015 non-null   float64
 3   harga_original  9015 non-null   float64
 4   diskon          9015 non-null   float64
 5   rating          5087 non-null   float64
 6   jumlah_review   9015 non-null   float64
 7   jumlah_terjual  0 non-null      float64
dtypes: float64(6), object(2)
memory usage: 563.6+ KB

toko                 0
nama_produk          0
harga                0
harga_original       0
diskon               0
rating            3928
jumlah_review        0
jumlah_terjual    9015
dtype: int64

# Menyimpan Dataset Watsons

In [ ]:
df.to_csv('product_watsons_clean.csv', index=False)
print("Dataset berhasil disimpan dengan nama 'product_watsons_clean.csv'!")

Dataset berhasil disimpan dengan nama 'product_watsons_clean.csv'!